#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: https://artfish-workshop.info
baseurl: 
title: アートフィッシュ工作室
description: アートフィッシュ工作室では横浜を中心に子ども向けアート・工作授業を行っています。出張授業も承っています。子どもたちが「水を得た魚のように」いきいきと創作するようなプログラムを提供しています。
avatar: 
# favicon: /favicon.ico
logo: /assets/img/m_txt_3.jpg
favicon: 
# language: ja
language: ja

#
# Icons
#
icons:
  rss: true
  email:
  github:
  bitbucket:
  twitter:
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-92519200-3
disqus:

#
# Localizations.
#
str_next: 次へ
str_prev: 前へ
str_read_more: 読み込み中...
str_search: 検索
str_recent_posts: 最近の投稿
str_show_all_posts: すべての投稿を表示

#
# Recent posts.
#
recent_posts_num: 10

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url:
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jemoji
  - jekyll-sitemap

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
